# Cookiecutter-rendered catalog definition for Harness IDP 2.0
# Docs: IDP 2.0 entity schema & fields (identifier/name/type/owner). TechDocs annotation. 
# - https://developer.harness.io/docs/internal-developer-portal/catalog/catalog-yaml/
# - https://developer.harness.io/docs/internal-developer-portal/techdocs/enable-docs/

apiVersion: harness.io/v1
kind: Component

# Machine-friendly unique key
identifier: parson_test_one

# Update the scope and org/project identifiers to match the Harness environment
scope: PROJECT
orgIdentifier: sandbox
projectIdentifier: parson

# Human display name
name: Parson Test One

# Common types: service | library | docs | delegate
type: service

# Owner can be user or group (e.g., group:platform-team)
owner: user:account/todd.parson@harness.io

metadata:
  namespace: default
  description: A sample Java application built with Spring Boot
  annotations:
    # TechDocs looks inside the app repo for this monorepo
    backstage.io/techdocs-ref: dir:.

    # Helpful for plugins/deeplinks
    github.com/project-slug: harness-idp-sandbox/parson-test-one
    # ATTENTION: UNCOMMENT THIS TO CONFIGURE THE GITHUB PLUGIN
    # github.com/project-readme-path: parson-test-one

    # Optional direct link to this app folder on default branch
    backstage.io/source-location: >-
      url:https://github.com/harness-idp-sandbox/parson-test-one/tree/main

  links:
    - title: Source repository
      url: https://github.com/harness-idp-sandbox/parson-test-one
    # ATTENTION: OBTAIN THE WEBSITE URL, REPLACE IT BELOW, AND UNCOMMENT THESE LINES.
    # - title: Website URL
    #   url: REPLACE_THIS_WITH_THE_GHA_OUTPUT_URL

  tags:
    - java
    
spec:
  lifecycle: experimental
  sourceCode:
    provider: Github
    repoName: parson-test-one
    connectorRef: parsonghharnessidpsandbox
    branch: main
    monoRepo: false
  # Add relationships later if/when they exist:
  # dependsOn:
  #   - component:default/some-backend
  # providesApis:
  #   - api:default/parson-test-one-api
